# Define a versao da API
apiVersion: v1
# Define o nome do objeto: PersistentVolumeClaim (PVC)
kind: PersistentVolumeClaim
# Define os Metadados do objeto
metadata:
  # Define o nome do objeto
  name:
    my-local-pvc
    # Define a label associada a este PVC
  labels:
    # Label usada para vincular este PVC ao PV
    type: local-pvc
# Define as especificacoes deste objeto
spec:
  # Define o nome da StorageClass usada para vincular o PV ao PVC
  storageClassName: manual
  # Define o modo de acesso: RWO, ROX, RWX, RWOP
  accessModes:
    - ReadWriteOnce
  # Define o recurso a ser usado do PV
  resources:
    requests:
      storage: 10Gi
  # Seletor a ser usado para vincular usando a label definida no PV
  selector:
    matchLabels:
      type: local-pv
