# Define o PVC que vai ser vinculado ao storageclass standard (default) que ja vem no cluster,
# O mesmo ira criar um PV e associar ao PVC logo em seguida associar aos PODS do deployment
# Por padrao o minikube ja vem com um storageclass configurado ao iniciar o cluster.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          volumeMounts:
            - mountPath: "/storage"
              name: my-volume
          ports:
            - containerPort: 80
              name: "http-server"
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pv-claim
