apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # "admin" codificado em base64
  POSTGRES_USER: YWRtaW4=
  # "teste" codificado em base64
  POSTGRES_PASSWORD: dGVzdGU=
